[package]
name = "minesweeper"
version = "0.1.0"
authors = ["Ticki <Ticki@users.noreply.github.com>"]

[dependencies.libterm]
git = "https://github.com/Ticki/libterm.git"
features = ["nightly"]

[[bin]]
name = "minesweeper"
path = "src/minesweeper.rs"

[[bin]]
name = "snake"
path = "src/snake/main.rs"
